### ISSUE TITLE
Homepage statistics should display Total # of payment transactions

### ISSUE THREAD

**Issue by gthoma17** [diem/explorer#60]

**Comment by mkollasch-vmware** [comment]
It seems that the best way to get this data is a query like this:
```gql
sentpayment_events_aggregate(where: {status: {_eq: 1}}) {
  aggregate {
    count
  }
}
```

**Comment by mkollasch-vmware** [comment]
We have pushed work on the branch https://github.com/diem/explorer/tree/60-total-payments will display the data as required, it's just extremely slow. (That slowness won't interfere with the rest of the page.) It can be merged right now if that's tolerable. Otherwise, we can find a way to enhance Analytics to display the needed data, but that will require some further discussion.

**Comment by gthoma17** [comment]
https://user-images.githubusercontent.com/1739196/146053148-fda34fe7-64f5-4c88-b8ed-df6fd01e4726.mov
